version: 2.1

jobs:

 test_build_deploy_loginms:
   working_directory: ~/repo
   docker:
    - image: circleci/openjdk:8-stretch
   environment:
    LOGIN_MS_TAG: s3851781/bk-login-microservices:latest


   steps:
    - checkout
    - setup_remote_docker

    - run:
        name: cd into login_ms
        command: |
          ls
          cd BackEnd/loginmicroservices
          ls
     #Dependencies
    - restore_cache:
        keys:
        - loginms-{{ checksum "pom.xml" }}
        - loginms-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
          - ~/.m2
        key: loginms-{{ checksum "pom.xml" }}

    #Test
    - run: mvn test

    # Build Image
    - run:
       name: build login microservices image
       command: |
         docker build . -t $LOGIN_MS_TAG
    # Run Image
    - run:
       name: run login microservices image
       command: |
         docker run -d $LOGIN_MS_TAG
    # Test Image
    - run:
       name: test login microservices image
       command: |
         docker run -e CI=true $LOGIN_MS_TAG mvn test

    # Deploy Image
    - run:
       name: login to DockerHub
       command: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

    - run:
       name: push backend (login microservices)
       command: |
         docker push $LOGIN_MS_TAG:latest

 test_build_deploy_bookms:
   docker:
    - image: circleci/openjdk:8-jdk
   environment:
    BOOK_MS_TAG: s3851781/bk-book-microservices
   working_directory: ~/

   steps:
    - checkout
    - setup_remote_docker

# test_build_deploy_react:
#   docker:
#    - image: circleci/node
#   environment:
#    BOOK_MS_TAG: s3851781/bk-react-webapp
#   working_directory: ~/
#
#   steps:
#    - checkout
#    - setup_remote_docker


workflows:
  build_test_push_app:
    jobs:
      - test_build_deploy_loginms
#      - test_build_deploy_bookms
#      - test_build_deploy_react
      
